Update Akka.TestKit.NUnit to NUnit v4 (3rd attempt)
AkkaNetContrib/Akka.TestKit.NUnit pull request #136
Opened 2024-09-04 02:27 UTC by milang

Fixes #111.

## Changes

This PR extends pull request #131 by @UrsMetz, which in turn builds on the work of @SeanKilleen in #112.

### Improvements in NUnit TestKit adapters

- ⚠️ `Akka.TestKit.NUnit`
    - Uses the latest NUnit 4 (`4.2.2`)
    - Targets `net6.0` and `net462`, just like NUnit 4
- ⚠️ `Akka.TestKit.NUnit3`
    -  Uses the latest NUnit 3 (`3.14.0`)
    - Targets `netstandard2.0`, just like NUnit 3
        - NUnit 3 actually supports `net35;net40;net45;netstandard2.0`, but we have to exclude frameworks not supported by `Akka.TestKit@1.5.27.1`
- Implementations of NUnit 4 and NUnit 3 adapters are now almost identical, both using constraint model. The only difference is how the assertion message is constructed, because NUnit 4 removed support for [format and params specification](https://docs.nunit.org/articles/nunit/release-notes/breaking-changes.html#nunit-40:~:text=Assert.That%20overloads%20with%20format%20specification%20and%20params%20have%20been%20removed%20in%20favor%20of%20an%20overload%20using%20FormattableString).
- `ITestKitAssertions.AssertEqual(..., comparer, ...)` now uses NUnit constraint model instead of custom assertion implementation. This makes failure reports more consistent with rest of NUnit output.
- All dependencies have been bumped to the latest version. Merging this PR should allow all existing dependabot pull requests to be closed (except `Nuke.Common`).

### Improvements in NuGet packages

- Icon and license are now specified by `PackageIcon` and `PackageLicenseExpression` properties, eliminating warnings during `dotnet pack`. Akka icon with dimensions 128x128px is now embedded in `.nupkg` file, as [recommended by NuGet](https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg#:~:text=Size%20recommendation%20%2D%20128x128).
- Symbol files (`.pdb`) are now included directly in the `.nupkg` files. This only increases the final `.nupkg` size by ~20 kB and removes the need to publish separate `.snupkg` file to a symbol server. See [Microsoft guidance](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages).
- Current year is automatically set in copyright message

The following screenshot compares currently published `.nupkg` file (version `1.5.24`) with `.nupkg` as proposed by this pull request. Please note that the green "source link", "deterministic exe/dll", and "compiler flags" shields typically require the package to be built with the latest .NET SDK (mine was built using .NET SDK 8.0.401). However this repository's GitHub Actions are currently configured to use .NET SDK 6.

<img width="1793" alt="Akka.TestKit.NUnit.nupkg comparison" src="https://github.com/user-attachments/assets/d90801cc-3403-498d-af07-96bb719a7789">

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

2024-09-05 03:31 UTC, FarrisPandell requested changes

2024-09-05 03:31 UTC, FarrisPandell commented on RELEASE_NOTES.md
> +   `Akka.TestKit.NUnit` targets NUnit 4, while `Akka.TestKit.NUnit` targets NUnit 3.
```suggestion
   `Akka.TestKit.NUnit` targets NUnit 4, while `Akka.TestKit.NUnit3` targets NUnit 3.
```

2024-09-06 19:00 UTC, milang commented on RELEASE_NOTES.md
> +   `Akka.TestKit.NUnit` targets NUnit 4, while `Akka.TestKit.NUnit` targets NUnit 3.
Updated.

2024-09-06 19:02 UTC, milang commented
@FarrisPandell addressed your feedback, ready for next round.

2024-09-06 19:13 UTC, FarrisPandell approved these changes

2024-09-06 19:15 UTC, milang commented
@Aaronontheweb any feedback for this pull request? I updated the `Akka.TestKit` dependency to `1.5.28`, new `Akka.TestKit.NUnit` release would nicely match yesterday's [Akka.NET release](https://github.com/akkadotnet/akka.net/releases/tag/1.5.28)?

2024-09-06 19:19 UTC, Aaronontheweb commented
@milang @FarrisPandell my apologies - I've had GitHub Notifications turned off for 10 years (unless I get explicitly mentioned), so this is the first I'm seeing this. CI/CD is failing - any idea what that's about?

2024-09-06 19:22 UTC, Aaronontheweb commented
Overall the NuGet package structure you've proposed looks good to me

2024-09-06 19:37 UTC, milang commented
@Aaronontheweb 

> CI/CD is failing - any idea what that's about?

Nuke is complaining that _"Release Notes should not be empty"_. I tracked it down to newlines that I added after version headers in `RELEASE_NOTES.md` - the newlines were recommended by `markdownlint`, but they were confusing Nuke build.

I pushed a new commit that removes the empty newlines, hopefully the build will pass now.

2024-09-06 20:25 UTC, Aaronontheweb commented
> @Aaronontheweb
> 
> > CI/CD is failing - any idea what that's about?
> 
> Nuke is complaining that _"Release Notes should not be empty"_. I tracked it down to newlines that I added after version headers in `RELEASE_NOTES.md` - the newlines were recommended by `markdownlint`, but they were confusing Nuke build.
> 
> I pushed a new commit that removes the empty newlines, hopefully the build will pass now.

Ugh, yes NUKE is very opinionated about this. Ran into that myself before.

2024-09-06 20:26 UTC, Aaronontheweb approved these changes
LGTM

2024-09-06 20:30 UTC, merged

2024-09-06 20:49 UTC, Aaronontheweb commented
So it's release as v1.6.0-preview1 on NuGet - let me know if that's acceptable

2024-09-06 20:50 UTC, Aaronontheweb commented
I'm also fine doing it as v1.5.* package if there's buy-in

2024-09-07 04:04 UTC, UrsMetz commented
@Aaronontheweb would a release as 1.6.* mean that a corresponding Akka 1.6.* was needed to use the NUnit v4 compatible version of Akka.TestKit.NUnit?
I think currently all Akka packages tend to share the same minor version.
My team is eagerly waiting for the NUnit 4 compatibility.

2024-09-08 02:02 UTC, SeanKilleen commented
@milang thanks for getting this across the finish line! Awesome work 🎉 👏

2024-09-09 17:19 UTC, milang commented
@Aaronontheweb 

> So it's release as v1.6.0-preview1 on NuGet - let me know if that's acceptable
> I'm also fine doing it as v1.5.* package if there's buy-in

@UrsMetz 

> Would a release as 1.6.* mean that a corresponding Akka 1.6.* was needed to use the NUnit v4 compatible version of Akka.TestKit.NUnit? I think currently all Akka packages tend to share the same minor version.

Sorry, I didn't realize that the major/minor version was fixed at `1.5` to match rest of Akka.NET. Initially I bumped to `1.6` to follow semantic versioning, indicating that major version of NUnit dependency changed. That being said, I have no issue with staying on `1.5`, and in light of Urs' comment that would be the better approach.

@Aaronontheweb don't forget to delete the [`VersionSuffix` line #7 in `Directory.Build.props`](https://github.com/akkadotnet/Akka.TestKit.NUnit/blob/dev/src/Directory.Build.props#L7) to remove the pre-release flag.

2024-09-16 16:06 UTC, milang commented
@Aaronontheweb any chance you could publish `Akka.TestKit.NUnit` as version `1.5.28` (see my comments from last week) ?

Also, I noticed that `Akka.TestKit.NUnit3` has not been published in a while, and is at version `1.3.8`:
<img width="805" alt="image" src="https://github.com/user-attachments/assets/4b26b8a1-bc78-483f-83bc-ccea41f7d187">

As per the changes in this PR, the latest build of `Akka.TestKit.NUnit3` should be published as version `1.5.28`. It can remain obsolete, but IMO the deprecation message should be updated from:

> This version is now deprecated - please use Akka.TestKit.NUnit (which also supports NUnit 3)

to:

> This version is now deprecated - please use Akka.TestKit.NUnit with NUnit 4.