Nuke
AkkaNetContrib/Akka.TestKit.NUnit pull request #47
Opened 2022-07-15 18:47 UTC by eaba

## Checklist

Build system is ancient here - need to bring over the https://github.com/petabridge/Petabridge.Library/ build engine.

2022-07-18 11:51 UTC, Aaronontheweb commented
@eaba does this work correctly locally?

2022-07-18 12:21 UTC, eaba commented
Not yet

2022-07-19 00:56 UTC, eaba commented
continuous-integration/teamcity @Aaronontheweb

2022-07-19 11:28 UTC, Aaronontheweb requested changes
@eaba there's an enormous number of binary files committed in this PR that should not be.  - all under the ./build/tools directory.

2022-07-19 18:35 UTC, eaba commented
@Aaronontheweb

2022-07-20 13:34 UTC, Aaronontheweb approved these changes
LGTM

2022-07-20 13:34 UTC, merged

2022-07-20 19:26 UTC, mchandschuh commented
Thanks for the quick turn around guys! 🙇

2022-07-20 19:28 UTC, mchandschuh commented on src/Akka.TestKit.NUnit/TestKit.cs
> +    [FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
This is my fault -- I overlooked this required change in the initial PR. We need to remove this throw (here)[https://github.com/akkadotnet/Akka.TestKit.NUnit/pull/47/commits/ae5a6e00ac19e8224a17d1b99538a3cac5809160#diff-835e2f8d56950585d517422fc80535cf17ae703f07536b0850e66b3f1fc256f1R38]

2022-07-20 19:32 UTC, mchandschuh commented on src/Akka.TestKit.NUnit/TestKit.cs
> +    [FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
A new unit test showing that we can pass `ActorSystem` to `TestKit.ctor` would be nice as well.